# Copyright (c) 2026 Pooria Askari Moqaddam. All rights reserved.
# Licensed under the Business Source License 1.1 (BUSL-1.1).
# See the LICENSE file in the project root for details.

name: sarvmd_workspace
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/sarvmd_core
  - apps/sarvmd_cli
  - apps/sarvmd_ui
