name: sarv_cli
description: CLI application for Sarv music score notebook.
publish_to: none
resolution: workspace
environment:
  sdk: ^3.6.0
dependencies:
  sarv_core:
    path: ../../packages/sarv_core
  args: ^2.5.0
