# Copyright (c) 2026 Pooria Askari Moqaddam. All rights reserved.
# Licensed under the Business Source License 1.1 (BUSL-1.1).
# See the LICENSE file in the project root for details.

name: sarvmd_cli
description: "Command-line interface tool for SarvMD music manuscript designer and LaTeX vector compiler."
homepage: https://github.com/pooriaaskarim/sarvmd
repository: https://github.com/pooriaaskarim/sarvmd
issue_tracker: https://github.com/pooriaaskarim/sarvmd/issues
documentation: https://github.com/pooriaaskarim/sarvmd#readme
publish_to: none
resolution: workspace
environment:
  sdk: ^3.6.0
dependencies:
  sarvmd_core:
    path: ../../packages/sarvmd_core
  args: ^2.5.0
  logd: ^0.9.1
