# Copyright (c) 2026 Pooria Askari Moqaddam. All rights reserved.
# Licensed under the Business Source License 1.1 (BUSL-1.1).
# See the LICENSE file in the project root for details.

name: sarvmd_ui
description: "A flexible, high-precision music manuscript designer for composers, educators, and engravers to create custom printable staff notebooks and layout designs."
version: 0.6.1
homepage: https://github.com/pooriaaskarim/sarvmd
repository: https://github.com/pooriaaskarim/sarvmd
issue_tracker: https://github.com/pooriaaskarim/sarvmd/issues
documentation: https://github.com/pooriaaskarim/sarvmd#readme
publish_to: 'none'
resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sarvmd_core:
    path: ../../packages/sarvmd_core
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^2.0.10
  flutter_driver:
    sdk: flutter
  shared_preferences: ^2.5.5
  flutter_bloc: ^8.1.6
  logd: ^0.9.1
  file_picker: ^8.1.7

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Bravura
      fonts:
        - asset: assets/fonts/Bravura.otf
    - family: IranNastaliq
      fonts:
        - asset: assets/fonts/IranNastaliq.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700

  assets:
    - assets/handwriting/
    - CHANGELOG.md
