name: sarvmd_ui
description: "A new Flutter project."
publish_to: 'none'
resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sarvmd_core:
    path: ../../packages/sarvmd_core
  flutter_svg: ^2.0.10
  flutter_driver:
    sdk: flutter
  shared_preferences: ^2.5.5

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NotoMusic
      fonts:
        - asset: assets/fonts/NotoMusic-Regular.ttf
    - family: IranNastaliq
      fonts:
        - asset: assets/fonts/IranNastaliq.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    - assets/handwriting/
